<?php

function motor_menu() {

  $items['ajax/get-model-description'] = array(
    'title' => 'motor_get_model_description',
    'page callback' => 'motor_get_model_description',
    'page argument' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function motor_get_config_photo($mail_body) {

  preg_match('/<div id="model-name">(.*?)<\/div>/ms', $mail_body, $model_match);
  $model = trim($model_match[1]);

  preg_match('/<div class="data-row-left exterior">(.*?)<\/div>/ms', $mail_body, $exterior_match);
  $exterior = trim($exterior_match[1]);

  preg_match('/<div class="data-row-left rim">(.*?)<\/div>/ms', $mail_body, $rim_match);
  $rim = trim($rim_match[1]);

  switch ($model) {
    case 'Tesla Model S':
      $model = 'modelS';

      if (strpos($rim, '19') !== FALSE) {
        $rim = '19silver';
      }
      elseif (strpos($rim, '19') !== FALSE && strpos($rim, 'sonic') !== FALSE) {
        $rim = '19sonic';
      }
      elseif (strpos($rim, '21') !== FALSE) {
        $rim = '21sonic';
      }
      else {
        $rim = 'empty';
      }
      break;

    case 'Tesla Model 3':
      $model = 'model3';

      if (strpos($rim, '18') !== FALSE) {
        $rim = '18aero';
      }
      elseif (strpos($rim, '19') !== FALSE) {
        $rim = '19sport';
      }
      elseif (strpos($rim, '20') !== FALSE) {
        $rim = 'performance';
      }
      else {
        $rim = 'empty';
      }

      break;

    case 'Tesla Model X':
      $model = 'modelX';

      if (strpos($rim, 'ezüst') !== FALSE) {
        $rim = '20silver';
      }
      elseif (strpos($rim, 'ezüst-fekete') !== FALSE) {
        $rim = '20slipstream';
      }
      elseif (strpos($rim, 'onyx') !== FALSE) {
        $rim = '22onyx';
      }
      else {
        $rim = 'empty';
      }
      break;

    case 'Tesla Model Y':
      $model = 'modelY';
      if (strpos($rim, '18') !== FALSE) {
        $rim = '18aero';
      }
      elseif (strpos($rim, '19') !== FALSE) {
        $rim = '19sport';
      }
      elseif (strpos($rim, '20') !== FALSE) {
        $rim = '20performance';
      }
      else {
        $rim = 'empty';
      }
      break;

    case 'Tesla Roadster':
      $model = 'roadster';
      break;
    
    default:
      $model = 'empty';
      break;
  }

  switch ($exterior) {
    case 'Gyémánt metál':
      $exterior = 'white';
      break;
    case 'Fekete metál':
      $exterior = 'black';
      break;
    case 'Sötétszürke metál':
      $exterior = 'silver';
      break;
    case 'Mélykék metál':
      $exterior = 'blue';
      break;
    case 'Vörös metál':
      $exterior = 'red';
      break;
    
    default:
      $exterior = 'empty';
      break;
  }

  $path = drupal_get_path('theme', 'tesla') . '/images/config-images/jpg/';
  $photo_name = 'https://tesla.hu/' . $path . $model . '_' . $exterior . '_' . $rim . '.jpg';

  return $photo_name;

}

function motor_get_model($mail_body) {

  preg_match('/<div id="model-name">(.*?)<\/div>/ms', $mail_body, $model_match);
  $model = trim($model_match[1]);

  return $model;

}

function motor_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'po_tesla_node_form') {
    $form['#attached']['js'][] = array(
      'data' => drupal_get_path('module', 'motor') . '/motor.js',
      'type' => 'file',
    );
  }
}

function motor_get_model_description($tid) {

  $model = taxonomy_term_load($tid);
  if (empty($model->description)) {
    $model = reset(taxonomy_get_parents($tid));
  } 
  drupal_json_output($model->description);

}

function motor_html_head_alter(&$head_elements) {
  global $base_url;
  // Get our current uri.
  $uri = drupal_get_path_alias();

  // We try to match it by forming the right key with the info we have.
  $key = 'drupal_add_html_head_link:canonical:</' . $uri . '>;';

  // Check that it is set, then we re-set it to the correct full url.
  if (isset($head_elements[$key])) {
    // Alter our head_element.
    $head_elements[$key]['#attributes']['href'] = $base_url . '/' .$uri;
  }
} 